"""Report generator - produces design review reports in Markdown format."""

from datetime import datetime
from typing import Optional

from .analyzer import DesignReport, DesignCheck, Severity


class DesignReporter:
    """Generate formatted design review reports."""

    def generate_markdown(self,
                          report: DesignReport,
                          suggestions: list,
                          design_name: str = "Unnamed Design",
                          design_state: Optional[dict] = None) -> str:
        """Generate a comprehensive Markdown design review report."""
        lines = []
        now = datetime.now().strftime("%Y-%m-%d %H:%M")

        lines.append(f"# Motor Design Review: {design_name}")
        lines.append(f"**Generated**: {now}")
        lines.append(f"**Overall Score**: {report.overall_score:.0f}/100")
        lines.append("")

        bar = self._score_bar(report.overall_score)
        lines.append("```")
        lines.append(f"Score: {bar} {report.overall_score:.0f}/100")
        lines.append("```")
        lines.append("")

        lines.append("## Summary")
        lines.append(f"- Critical issues: **{report.critical_count}**")
        lines.append(f"- Warnings: **{report.warning_count}**")
        ok_count = len(report.checks) - report.critical_count - report.warning_count
        lines.append(f"- Parameters OK: **{ok_count}**")
        lines.append("")

        if design_state:
            lines.append("## Current Design State")
            geo = design_state.get("geometry", {})
            if geo:
                lines.append("### Geometry")
                lines.append("| Parameter | Value |")
                lines.append("|---|---|")
                for k, v in geo.items():
                    if v is not None:
                        lines.append(f"| {k} | {v:.3f} |")
                lines.append("")

        lines.append("## Detailed Analysis")
        categories = {}
        for check in report.checks:
            cat = check.category
            if cat not in categories:
                categories[cat] = []
            categories[cat].append(check)

        for cat, checks in categories.items():
            lines.append(f"### {cat.title()}")
            lines.append("| Status | Parameter | Value | Expected Range |")
            lines.append("|---|---|---|---|")
            for c in checks:
                icon = self._severity_icon(c.severity)
                lines.append(
                    f"| {icon} | {c.name} | {c.value:.2f} {c.unit} | "
                    f"[{c.range_min} - {c.range_max}] {c.unit} |"
                )
            lines.append("")

        if suggestions:
            lines.append("## Improvement Suggestions")
            lines.append("")
            for s in suggestions:
                labels = {1: "P1-Critical", 2: "P2-High", 3: "P3-Medium",
                          4: "P4-Low", 5: "P5-Nice-to-have"}
                label = labels.get(s.priority, f"P{s.priority}")
                lines.append(f"### [{label}] {s.title}")
                lines.append("")
                lines.append(f"**Detail**: {s.detail}")
                lines.append("")
                lines.append(f"- Category: {s.category}")
                lines.append(f"- Expected Impact: {s.expected_impact}")
                lines.append(f"- Effort: {s.effort}")
                lines.append("")

        lines.append("---")
        lines.append("*Report generated by AI Motor Design Assistant v0.1.0*")

        return "\n".join(lines)

    def save_report(self, content: str, filepath: str):
        """Save report to file."""
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)

    def generate_quick_summary(self, report: DesignReport) -> str:
        """Generate a one-paragraph quick summary."""
        if report.critical_count == 0 and report.warning_count == 0:
            return "All checks passed. Design looks good!"
        parts = []
        if report.critical_count:
            parts.append(f"{report.critical_count} critical issue(s) found")
        if report.warning_count:
            parts.append(f"{report.warning_count} warning(s)")
        return f"Design score: {report.overall_score:.0f}/100. " + ", ".join(parts) + "."

    def _score_bar(self, score: float) -> str:
        filled = int(score / 5)
        empty = 20 - filled
        return "[" + "#" * filled + "-" * empty + "]"

    def _severity_icon(self, severity: Severity) -> str:
        return {Severity.OK: "OK", Severity.INFO: "INFO",
                Severity.WARNING: "WARN", Severity.CRITICAL: "CRIT"}.get(severity, "??")